name: Market Research

on:
  schedule:
    - cron: '0 9 * * 5'   # 毎週金曜 9時(JST換算なら調整が必要)
  workflow_dispatch:       # 手動実行も可能

jobs:
  run-research:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run market research
        run: |
          python market_research.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: market-research-report
          path: results.json
